apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ibs-dev-qfc-kitchen

resources:
- ../../base

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/part-of: ibs-dev-qfc-kitchen

images:
- name: ibs-qfc-kitchen-web
  newName: registry.apps.ibsolution.cloud/ibs/ibs-qfc-kitchen/web
  newTag: 1.3.2-dev.a3d1e3c
