-- Production seed transition: purge the demo rows the pre-production first-
-- run seed wrote and let the new minimal baseline re-seed.
--
-- Background
-- ----------
-- The first-run seed (api/seed/seed.json, generated by tools/gen-seed.ts)
-- used to ship the full MOCK_* demo dataset from web/src/constants.ts:
-- employees e1-e4, projects p1-p14, customers c1-c12, plan versions v1-v4
-- (with assignments/absences/quarter_data), the DE-2026 public holidays,
-- strategic goals sg1-sg6, north stars ns1-ns4, and 1:1 sessions 1o1_1..4.
-- Databases that booted before this migration therefore carry exactly those
-- rows. The production baseline is different: no employees, no calendar
-- data, no plan versions - just the single internal customer
-- "IBsolution GmbH" (id `ibs`), and account creation moved entirely to the
-- auth layer (QFC_ADMIN_EMAILS, QFC_DEFAULT_ROLE).
--
-- This migration therefore:
--   1. deletes exactly the rows the old seed created (id lists frozen from
--      the committed pre-production seed.json - never user-created rows),
--   2. removes the `meta.seeded` marker, so the new minimal seed (which now
--      writes only the internal customer) runs right after migrations, and
--   3. leaves every other table - users first among them - untouched: the
--      configured Admin account(s) survive the transition.
--
-- The `users` table is deliberately NOT touched: deleting accounts would
-- fight the auth layer (`auth::ensure_admins`), and the whole point of the
-- re-seed is that the only user is the one defined by QFC_ADMIN_EMAILS.

-- Plan versions cascade to assignment/absence/quarter_data (ON DELETE
-- CASCADE), so deleting the versions clears the planner rows too.
DELETE FROM plan_version WHERE id IN ('v1', 'v2', 'v3', 'v4');

DELETE FROM public_holiday WHERE (date, location) IN (
    ('2026-01-01', 'DE'),
    ('2026-04-03', 'DE'),
    ('2026-04-06', 'DE'),
    ('2026-05-01', 'DE'),
    ('2026-05-14', 'DE'),
    ('2026-05-25', 'DE'),
    ('2026-10-03', 'DE'),
    ('2026-12-25', 'DE'),
    ('2026-12-26', 'DE')
);

-- Blob tables: one row per seed id. project references customers only by
-- the (non-FK) client name, so there is no referential ordering concern.
DELETE FROM employee WHERE id IN ('e1', 'e2', 'e3', 'e4');
DELETE FROM customer WHERE id IN (
    'c1', 'c2', 'c3', 'c4', 'c5', 'c6',
    'c7', 'c8', 'c9', 'c10', 'c11', 'c12'
);
DELETE FROM project WHERE id IN (
    'p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7',
    'p8', 'p9', 'p10', 'p11', 'p12', 'p13', 'p14'
);
DELETE FROM strategic_goal WHERE id IN ('sg1', 'sg2', 'sg3', 'sg4', 'sg5', 'sg6');
DELETE FROM north_star WHERE id IN ('ns1', 'ns2', 'ns3', 'ns4');
DELETE FROM one_on_one WHERE id IN ('1o1_1', '1o1_2', '1o1_3', '1o1_4');

-- Drop the old-seed completion marker: `seed::seed_if_empty` runs after
-- migrations and re-seeds the new production baseline (the internal
-- customer) on every database that reached this point with the marker set.
-- On fresh installs this is a no-op (no marker, no rows) and the first
-- seed run proceeds as before.
DELETE FROM meta WHERE key = 'seeded';
