//! First-run seed pipeline: loads `seed/seed.json` — generated by
//! `tools/gen-seed.ts` from `web/src/constants.ts`'s mock data, through the
//! same `*ToProto` adapters (`web/src/api/adapters.ts`) the web app itself
//! uses, see that script's doc comment — into an empty database exactly
//! once, so a freshly built image comes up already carrying today's demo
//! data with no separate deploy-time step.
//!
//! # Id collisions across plan versions (and how this module avoids them)
//!
//! `web/src/constants.ts`'s `MOCK_VERSIONS` reuse the *same* `Assignment`/
//! `Absence` objects (and therefore the same `id`s) across multiple plan
//! versions — e.g. `ASSIGNMENTS_Q1_2026_ADJUSTED` is `[...ASSIGNMENTS_Q1_2026_INITIAL,
//! ...]`, so `id: 'a1'` appears once per version it was spread into. That is
//! harmless for the mock/local-storage prototype (each version keeps its own
//! assignments array), but `migrations/0001_init.sql`'s `assignment`/
//! `absence` tables key `id` as a single, version-*spanning* `PRIMARY KEY` —
//! only `(version_id, employee_id, project_id, date)` /
//! `(version_id, employee_id, date)` are scoped per version (their unique
//! indexes). Inserting the seed's `Assignment.id`/`Absence.id` values
//! verbatim therefore collides the moment a second version reuses one.
//!
//! [`insert_plan_version`] works around this the same way a fresh
//! `ApplyAssignments`/`ApplyAbsences` call would if it always created
//! (never updated) a row: it writes a version-namespaced primary key
//! (`"{version_id}:{original_id}"`) instead of the JSON's own `id`, which is
//! already unique *within* one version (verified by inspection of the
//! generated `seed/seed.json`) and therefore globally unique once
//! namespaced. `quarter_data` needs no such treatment — its primary key is
//! the compound `(version_id, id)`, already scoped per version.
//!
//! Separately, the *unique index* on `(version_id, employee_id, project_id,
//! date)` — the "one employee/project/date combination is one cell"
//! invariant `services::planning::resolve_assignment_id` documents — is
//! genuinely violated twice by the generated fixture: `v3`'s
//! `ASSIGNMENTS_Q2_2026` array both spreads `ASSIGNMENTS_Q1_2026_ADJUSTED`
//! (which already assigns e2/e1 to p3 via `generateSokaBauAssignments`) and
//! appends a couple of manually authored cells (`b2`, `b4`) for those exact
//! same employee/project/date combinations. That is a real double-booking
//! in the demo data, not a bug in this pipeline; the assignment insert below
//! therefore upserts on that unique index (last one in array order wins),
//! mirroring `do_apply_assignments`'s own "existing cell wins the id, new
//! values win the content" semantics rather than failing the whole seed.

use buffa::{EnumValue, Enumeration, Message};
use serde::Deserialize;
use sqlx::{SqliteConnection, SqlitePool};

use crate::error::{AppError, AppResult};
use crate::proto::crm::Customer;
use crate::proto::growth::OneOnOneSession;
use crate::proto::planning::{AbsenceType, PlanVersion, PublicHoliday};
use crate::proto::portfolio::Project;
use crate::proto::strategy::{NorthStarMetric, StrategicGoal};
use crate::proto::team::Employee;
use crate::store::{self, Table};
use crate::time::now_millis;

/// The generated seed artifact (see this module's doc comment). Embedded at
/// compile time, so a malformed file is a build-time asset, not a runtime
/// fetch that could go missing.
const SEED_JSON: &str = include_str!("../seed/seed.json");

/// The `meta` key marking that the first-run seed has completed. Its value
/// is the epoch-millis timestamp the seed committed at — informational only,
/// never read back by [`seed_if_empty`] itself; presence of the row is the
/// only thing that matters.
const SEEDED_META_KEY: &str = "seeded";

/// Top-level shape of `seed/seed.json`, matching `tools/gen-seed.ts`'s
/// `seed` object key for key. Every field defaults to empty so a seed file
/// missing an optional collection degrades to "nothing of that kind" rather
/// than a hard parse failure.
#[derive(Debug, Default, Deserialize)]
struct SeedData {
    #[serde(default)]
    employees: Vec<Employee>,
    #[serde(default)]
    projects: Vec<Project>,
    #[serde(default)]
    customers: Vec<Customer>,
    #[serde(default)]
    versions: Vec<PlanVersion>,
    #[serde(default)]
    holidays: Vec<PublicHoliday>,
    #[serde(default)]
    goals: Vec<StrategicGoal>,
    #[serde(default, rename = "northStars")]
    north_stars: Vec<NorthStarMetric>,
    #[serde(default, rename = "oneOnOnes")]
    one_on_ones: Vec<OneOnOneSession>,
}

/// Seed the database from the embedded `seed/seed.json` if (and only if) it
/// has never been seeded before. Returns `Ok(true)` if this call performed
/// the seed, `Ok(false)` if a prior run already had.
///
/// Called once at startup, right after migrations run and before the server
/// starts accepting connections (see `main.rs`) — a malformed seed file
/// therefore fails process startup outright (via the caller's `.expect(...)`)
/// rather than silently booting an empty app.
pub async fn seed_if_empty(pool: &SqlitePool) -> AppResult<bool> {
    seed_from_json(pool, SEED_JSON).await
}

/// The testable core of [`seed_if_empty`]: takes the seed JSON as a plain
/// `&str` parameter (rather than reaching for the embedded [`SEED_JSON`]
/// directly) so `tests/seed.rs` can exercise this against both the real
/// seed file and a deliberately corrupted string, using a real (temp)
/// database either way.
pub async fn seed_from_json(pool: &SqlitePool, json: &str) -> AppResult<bool> {
    if already_seeded(pool).await? {
        return Ok(false);
    }

    let mut raw: serde_json::Value = serde_json::from_str(json)
        .map_err(|err| AppError::Internal(format!("seed/seed.json is malformed: {err}")))?;
    decimalize_project_hourly_rates(&mut raw);
    let data: SeedData = serde_json::from_value(raw)
        .map_err(|err| AppError::Internal(format!("seed/seed.json is malformed: {err}")))?;

    let mut tx = pool.begin().await?;

    for employee in &data.employees {
        store::upsert_blob(&mut tx, Table::Employee, &employee.id, employee).await?;
    }
    for project in &data.projects {
        store::upsert_blob(&mut tx, Table::Project, &project.id, project).await?;
    }
    for customer in &data.customers {
        store::upsert_blob(&mut tx, Table::Customer, &customer.id, customer).await?;
    }
    for goal in &data.goals {
        store::upsert_blob(&mut tx, Table::StrategicGoal, &goal.id, goal).await?;
    }
    for metric in &data.north_stars {
        store::upsert_blob(&mut tx, Table::NorthStar, &metric.id, metric).await?;
    }
    for session in &data.one_on_ones {
        insert_one_on_one(&mut tx, session).await?;
    }

    let mut assignment_count = 0usize;
    let mut absence_count = 0usize;
    let mut quarter_data_count = 0usize;
    for version in &data.versions {
        let counts = insert_plan_version(&mut tx, version).await?;
        assignment_count += counts.0;
        absence_count += counts.1;
        quarter_data_count += counts.2;
    }

    for holiday in &data.holidays {
        insert_public_holiday(&mut tx, holiday).await?;
    }

    mark_seeded(&mut tx).await?;

    tx.commit().await?;

    tracing::info!(
        employees = data.employees.len(),
        projects = data.projects.len(),
        customers = data.customers.len(),
        plan_versions = data.versions.len(),
        assignments = assignment_count,
        absences = absence_count,
        quarter_data = quarter_data_count,
        holidays = data.holidays.len(),
        goals = data.goals.len(),
        north_stars = data.north_stars.len(),
        one_on_ones = data.one_on_ones.len(),
        "seeded empty database with first-run demo data"
    );

    Ok(true)
}

/// Rewrite every `projects[].hourlyRate` JSON *number* to its decimal
/// string form, in place, before `raw` is deserialized into the proto types.
///
/// `qfc.portfolio.v1.Project.hourly_rate` is an `optional string` (a
/// decimal, exact by construction), but the seed data originates from
/// `web/src/constants.ts`'s `hourlyRate: number`, so the generated artifact
/// carries JSON numbers there. Rust's `f64` `Display` already produces the
/// shortest round-trip form — integral values with no fraction (`110` →
/// `"110"`, `0` → `"0"`), otherwise the minimal decimal (`97.5` →
/// `"97.5"`) — which is exactly the canonical form the proto field
/// documents. Values already in string form (e.g. after a regeneration
/// whose adapters emit strings) pass through untouched; absent rates
/// (proto3-JSON omits unset optionals) are left absent.
fn decimalize_project_hourly_rates(raw: &mut serde_json::Value) {
    let Some(projects) = raw.get_mut("projects").and_then(|p| p.as_array_mut()) else {
        return;
    };
    for project in projects {
        let Some(rate) = project.get_mut("hourlyRate") else {
            continue;
        };
        if let Some(number) = rate.as_f64() {
            *rate = serde_json::Value::String(format!("{number}"));
        }
    }
}

/// `true` if the `meta` table already carries a `seeded` row — the cheap
/// check [`seed_from_json`] runs before doing any real work.
async fn already_seeded(pool: &SqlitePool) -> AppResult<bool> {
    let found: Option<i64> = sqlx::query_scalar("SELECT 1 FROM meta WHERE key = ?1")
        .bind(SEEDED_META_KEY)
        .fetch_optional(pool)
        .await?;
    Ok(found.is_some())
}

/// Write the `meta` row marking the seed complete, stamped with the current
/// time. Writing this in the same transaction as every other seed row is
/// what makes a partial seed impossible to observe as "done": either the
/// whole transaction (data + this marker) commits, or none of it does.
async fn mark_seeded(conn: &mut SqliteConnection) -> AppResult<()> {
    sqlx::query("INSERT INTO meta (key, value) VALUES (?1, ?2)")
        .bind(SEEDED_META_KEY)
        .bind(now_millis().to_string())
        .execute(&mut *conn)
        .await?;
    Ok(())
}

/// Insert one `one_on_one` row, matching `services::growth`'s write shape
/// (an extra `employee_id` column kept in sync with the encoded blob — see
/// that module's doc comment for why `one_on_one` isn't a plain
/// `store::Table` blob table). A plain `INSERT` (no `ON CONFLICT`) is enough
/// here: seeding only ever runs once, against an empty table.
async fn insert_one_on_one(
    conn: &mut SqliteConnection,
    session: &OneOnOneSession,
) -> AppResult<()> {
    sqlx::query(
        "INSERT INTO one_on_one (id, employee_id, updated_at, data) VALUES (?1, ?2, ?3, ?4)",
    )
    .bind(&session.id)
    .bind(&session.employee_id)
    .bind(now_millis())
    .bind(session.encode_to_vec())
    .execute(&mut *conn)
    .await?;
    Ok(())
}

/// Insert one `plan_version` row plus its assignments/absences/quarter_data,
/// matching `services::planning`'s typed-column writes (see that module's
/// doc comment on why these tables use typed columns rather than an encoded
/// blob) — except for the assignment/absence primary key namespacing
/// described in this module's top-level doc comment.
///
/// Returns `(assignments inserted, absences inserted, quarter_data inserted)`
/// for the caller's summary log line.
async fn insert_plan_version(
    conn: &mut SqliteConnection,
    version: &PlanVersion,
) -> AppResult<(usize, usize, usize)> {
    let meta = version.meta.as_option().ok_or_else(|| {
        AppError::Internal("seed plan version is missing its required meta".to_string())
    })?;

    sqlx::query("INSERT INTO plan_version (id, name, description, created_at, updated_at) VALUES (?1, ?2, ?3, ?4, ?5)")
        .bind(&meta.id)
        .bind(&meta.name)
        .bind(meta.description.as_deref())
        .bind(meta.created_at_millis)
        .bind(now_millis())
        .execute(&mut *conn)
        .await?;

    for assignment in &version.assignments {
        // See this module's top-level doc comment: the seed's own
        // `assignment.id` is only unique within its version, but the
        // `assignment` table's primary key spans every version.
        let id = format!("{}:{}", meta.id, assignment.id);
        sqlx::query(
            "INSERT INTO assignment (id, version_id, employee_id, project_id, date, allocation) VALUES (?1, ?2, ?3, ?4, ?5, ?6)
             ON CONFLICT(version_id, employee_id, project_id, date) DO UPDATE SET id = excluded.id, allocation = excluded.allocation",
        )
        .bind(&id)
        .bind(&meta.id)
        .bind(&assignment.employee_id)
        .bind(&assignment.project_id)
        .bind(&assignment.date)
        .bind(assignment.allocation)
        .execute(&mut *conn)
        .await?;
    }

    for absence in &version.absences {
        // Same namespacing rationale as the assignment loop above.
        let id = format!("{}:{}", meta.id, absence.id);
        sqlx::query(
            "INSERT INTO absence (id, version_id, employee_id, date, absence_type, approved) VALUES (?1, ?2, ?3, ?4, ?5, ?6)",
        )
        .bind(&id)
        .bind(&meta.id)
        .bind(&absence.employee_id)
        .bind(&absence.date)
        .bind(absence_type_to_db(absence.absence_type))
        .bind(absence.approved)
        .execute(&mut *conn)
        .await?;
    }

    for (position, quarter) in version.forecast_data.iter().enumerate() {
        sqlx::query(
            "INSERT INTO quarter_data (id, version_id, position, data) VALUES (?1, ?2, ?3, ?4)",
        )
        .bind(&quarter.id)
        .bind(&meta.id)
        .bind(position as i64)
        .bind(quarter.encode_to_vec())
        .execute(&mut *conn)
        .await?;
    }

    // Not simply `version.assignments.len()`: the upsert above can collapse
    // more than one seed entry onto the same cell (see this module's
    // top-level doc comment), so the actual row count is read back rather
    // than assumed equal to the input length.
    let assignment_rows: i64 =
        sqlx::query_scalar("SELECT COUNT(*) FROM assignment WHERE version_id = ?1")
            .bind(&meta.id)
            .fetch_one(&mut *conn)
            .await?;

    Ok((
        assignment_rows as usize,
        version.absences.len(),
        version.forecast_data.len(),
    ))
}

async fn insert_public_holiday(
    conn: &mut SqliteConnection,
    holiday: &PublicHoliday,
) -> AppResult<()> {
    sqlx::query("INSERT INTO public_holiday (date, location, name) VALUES (?1, ?2, ?3)")
        .bind(&holiday.date)
        .bind(&holiday.location)
        .bind(&holiday.name)
        .execute(&mut *conn)
        .await?;
    Ok(())
}

/// Render an `EnumValue<AbsenceType>` for storage in `absence.absence_type
/// TEXT`, as its proto variant name (e.g. `"ABSENCE_TYPE_VACATION"`) —
/// mirrors `services::planning::absence_type_to_db`, which is private to
/// that module (and `api/src/services/**` is out of this module's remit to
/// change), so the few lines are duplicated here rather than shared.
fn absence_type_to_db(value: EnumValue<AbsenceType>) -> String {
    value
        .as_known()
        .unwrap_or(AbsenceType::Unspecified)
        .proto_name()
        .to_string()
}
