server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;

    location = /healthz {
        access_log off;
        add_header Content-Type text/plain;
        return 200 "ok\n";
    }

    location = / {
        return 302 /ibs-qfc-kitchen/;
    }

    location /ibs-qfc-kitchen/ {
        try_files $uri $uri/ /ibs-qfc-kitchen/index.html;
    }
}
