apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ibs-qfc-kitchen-api-data
  labels:
    app.kubernetes.io/part-of: ibs-qfc-kitchen
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
