apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ibs-qfc-kitchen-data
  labels:
    app.kubernetes.io/part-of: ibs-qfc-kitchen
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: <replace>
  storageClassName: hcloud-volumes
  resources:
    requests:
      storage: <replace>
